---

- hosts: localhost
  gather_facts: no
  vars_prompt:
  - name: target_host
    prompt: Please enter IP address  or domain name of admin node. (e.g. sandbox-kfk-admin)
    private: no

  tasks:
    - add_host:
        name: "{{ target_host }}"
        groups: dynamically_created_hosts

- hosts: dynamically_created_hosts
  become: true
  roles:
    - openjdk
    - ca-common
  vars:
    - doc_root: ~/ansible-kafka
