---
- hosts: localhost
  gather_facts: no
  vars_prompt:
  - name: target_host
    prompt: Please enter IP address  or domain name of broker (e.g. sandbox-kfk-bro1)
    private: no

  tasks:
    - add_host:
        name: "{{ target_host }}"
        groups: dynamically_created_hosts

- hosts: dynamically_created_hosts
  become: true
  roles:
    - import-cert
  vars:
    - doc_root: ~/ansible-kafka
