---

- name: Import truststore certificates in broker
  become_user: "{{ kafkaUser }}"
  shell: |
     {{ keytool_command }} -keystore {{ truststore_file }} \
     -alias {{ alias }} \
     -import -file {{ cert_file  }} \
     -storepass  "{{ password }}" \
     -keypass "{{ password }}" \
     -noprompt
  args:
     chdir: "{{ CSR_location }}"

- name: Import keystore certificates in broker
  become_user: "{{ kafkaUser }}"
  shell: |
     {{ keytool_command }} -keystore {{ keystore_file }} \
     -alias {{ alias }} \
     -import -file {{ cert_file  }} \
     -storepass  "{{ password }}" \
     -keypass "{{ password }}" \
     -noprompt
  args:
     chdir: "{{ CSR_location }}"

- name: Import signed certificates in broker
  become_user: "{{ kafkaUser }}"
  shell: |
     {{ keytool_command }} -keystore {{ keystore_file }} \
     -import -file {{ signed_cert  }} \
     -storepass  "{{ password }}" \
     -keypass "{{ password }}" \
     -noprompt
  args:
     chdir: "{{ CSR_location }}" 

- name: Stop Kafka
  become_user: "{{ kafkaUser }}"
  shell: "{{ kfk_home }}/bin/kafka-server-stop"
  ignore_errors: yes
  args:
    executable: /bin/bash

- name: Pause for 10 seconds 
  pause:
     seconds: 10

- name: Create custom kafka startup script
  become_user: "{{ kafkaUser }}"
  copy:
    dest: "{{ kfk_home }}/bin/kfkstart.sh"
    mode: 0755
    content: |
      {{ kfk_home  }}/bin/kafka-server-start -daemon {{ kfk_home }}/etc/kafka/server.properties


- name: Start Kafka
  become_user: "{{ kafkaUser }}"  
  shell: "{{ kfk_home }}/bin/kfkstart.sh"
  args:
     executable: /bin/bash

